spring:
  application:
    name: backend
    
  # Désactiver Docker Compose pour le développement
  docker:
    compose:
      enabled: false

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/support_db
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  
  session:
    store-type: redis
    redis:
      flush-mode: on_save

server:
  port: 8083

logging:
  level:
    com.cpierres.p13.poc: DEBUG
    org.springframework.web.socket: DEBUG